#include "KclUtil.hpp"

IMPORT_STD;

static std::array<KclType, 32> KclTypes = {
    KclType{.id = 0x00, .form = Form::Standard, .name = "/*0x00*/ [WIKI] Road"},
    KclType{.id = 0x01,
            .form = Form::Standard,
            .name = "/*0x01*/ [WIKI] Slippery Road 1"},
    KclType{.id = 0x02,
            .form = Form::Standard,
            .name = "/*0x02*/ [WIKI] Weak Off-road"},
    KclType{
        .id = 0x03, .form = Form::Standard, .name = "/*0x03*/ [WIKI] Off-road"},
    KclType{.id = 0x04,
            .form = Form::Standard,
            .name = "/*0x04*/ [WIKI] Heavy Off-road"},
    KclType{.id = 0x05,
            .form = Form::Standard,
            .name = "/*0x05*/ [WIKI] Slippery Road 2"},
    KclType{.id = 0x06,
            .form = Form::Standard,
            .name = "/*0x06*/ [WIKI] Boost Pad"},
    KclType{.id = 0x07,
            .form = Form::Standard,
            .name = "/*0x07*/ [WIKI] Boost Ramp"},
    KclType{
        .id = 0x08, .form = Form::Standard, .name = "/*0x08*/ [WIKI] Jump Pad"},
    KclType{.id = 0x09,
            .form = Form::Standard,
            .name = "/*0x09*/ [WIKI] Item Road"},
    KclType{.id = 0x0A,
            .form = Form::Standard,
            .name = "/*0x0A*/ [WIKI] Solid Fall"},
    KclType{.id = 0x0B,
            .form = Form::Indexed,
            .name = "/*0x0B*/ [WIKI] Moving Water"},
    KclType{.id = 0x0C, .form = Form::UNKNOWN, .name = "/*0x0C*/ [WIKI] Wall"},
    KclType{.id = 0x0D,
            .form = Form::UNKNOWN,
            .name = "/*0x0D*/ [WIKI] Invisible Wall"},
    KclType{
        .id = 0x0E, .form = Form::UNKNOWN, .name = "/*0x0E*/ [WIKI] Item Wall"},
    KclType{
        .id = 0x0F, .form = Form::UNKNOWN, .name = "/*0x0F*/ [WIKI] Wall 3"},
    KclType{.id = 0x10,
            .form = Form::UNKNOWN,
            .name = "/*0x10*/ [WIKI] Fall Boundary"},
    KclType{.id = 0x11,
            .form = Form::Indexed,
            .name = "/*0x11*/ [WIKI] Cannon Activator"},
    KclType{.id = 0x12,
            .form = Form::UNKNOWN,
            .name = "/*0x12*/ [WIKI] Force Recalculation"},
    KclType{.id = 0x13,
            .form = Form::UNKNOWN,
            .name = "/*0x13*/ [WIKI] Half-pipe Ramp"},
    KclType{.id = 0x14, .form = Form::UNKNOWN, .name = "/*0x14*/ [WIKI] Wall"},
    KclType{.id = 0x15,
            .form = Form::Indexed,
            .name = "/*0x15*/ [WIKI] Moving Road"},
    KclType{.id = 0x16,
            .form = Form::Standard,
            .name = "/*0x16*/ [WIKI] Sticky/Gravity Road"},
    KclType{.id = 0x17, .form = Form::Standard, .name = "/*0x17*/ [WIKI] Road"},
    KclType{.id = 0x18,
            .form = Form::UNKNOWN,
            .name = "/*0x18*/ [WIKI] Sound Trigger"},
    KclType{
        .id = 0x19, .form = Form::UNKNOWN, .name = "/*0x19*/ [WIKI] Unknown"},
    KclType{.id = 0x1A,
            .form = Form::UNKNOWN,
            .name = "/*0x1A*/ [WIKI] Effect Trigger"},
    KclType{.id = 0x1B,
            .form = Form::UNKNOWN,
            .name = "/*0x1B*/ [WIKI] Item State Modifier"},
    KclType{.id = 0x1C,
            .form = Form::UNKNOWN,
            .name = "/*0x1C*/ [WIKI] Half-pipe Invisible Wall"},
    KclType{.id = 0x1D,
            .form = Form::Standard,
            .name = "/*0x1D*/ [WIKI] Moving Road"},
    KclType{.id = 0x1E,
            .form = Form::UNKNOWN,
            .name = "/*0x1E*/ [WIKI] Special Walls"},
    KclType{
        .id = 0x1F, .form = Form::UNKNOWN, .name = "/*0x1F*/ [WIKI] Wall 5"},
};

const KclType& GetKCLType(u32 attr) { return KclTypes[attr & 31]; }
