#include "ObjUtil.hpp"

namespace riistudio::lvl {

const char* GetNameOfObject(int id) {
  switch (id) {
  case 0x001:
    return "airblock";
  case 0x002:
    return "Psea";
  case 0x003:
    return "lensFX";
  case 0x004:
    return "venice_nami";
  case 0x005:
    return "sound_river";
  case 0x006:
    return "sound_water_fall";
  case 0x007:
    return "pocha";
  case 0x008:
    return "sound_lake";
  case 0x009:
    return "sound_big_fall";
  case 0x00a:
    return "sound_sea";
  case 0x00b:
    return "sound_fountain";
  case 0x00c:
    return "sound_volcano";
  case 0x00d:
    return "sound_audience";
  case 0x00e:
    return "sound_big_river";
  case 0x00f:
    return "sound_sand_fall";
  case 0x010:
    return "sound_lift";
  case 0x011:
    return "pochaYogan";
  case 0x012:
    return "entry";
  case 0x013:
    return "pochaMori";
  case 0x014:
    return "eline_control";
  case 0x015:
    return "sound_Mii";
  case 0x016:
    return "begoman_manager";
  case 0x017:
    return "ice";
  case 0x018:
    return "startline2D";
  case 0x065:
    return "itembox";
  case 0x066:
    return "DummyPole";
  case 0x067:
    return "flag";
  case 0x068:
    return "flagBlend";
  case 0x069:
    return "gnd_sphere";
  case 0x06a:
    return "gnd_trapezoid";
  case 0x06b:
    return "gnd_wave1";
  case 0x06c:
    return "gnd_wave2";
  case 0x06d:
    return "gnd_wave3";
  case 0x06e:
    return "gnd_wave4";
  case 0x06f:
    return "sun";
  case 0x070:
    return "woodbox";
  case 0x071:
    return "KmoonZ";
  case 0x072:
    return "sunDS";
  case 0x073:
    return "coin";
  case 0x074:
    return "ironbox";
  case 0x075:
    return "ItemDirect";
  case 0x076:
    return "s_itembox";
  case 0x077:
    return "pile_coin";
  case 0x0c9:
    return "f_itembox";
  case 0x0ca:
    return "MashBalloonGC";
  case 0x0cb:
    return "WLwallGC";
  case 0x0cc:
    return "CarA1";
  case 0x0cd:
    return "basabasa";
  case 0x0ce:
    return "HeyhoShipGBA";
  case 0x0cf:
    return "koopaBall";
  case 0x0d0:
    return "kart_truck";
  case 0x0d1:
    return "car_body";
  case 0x0d2:
    return "skyship";
  case 0x0d3:
    return "w_woodbox";
  case 0x0d4:
    return "w_itembox";
  case 0x0d5:
    return "w_itemboxline";
  case 0x0d6:
    return "VolcanoBall1";
  case 0x0d7:
    return "penguin_s";
  case 0x0d8:
    return "penguin_m";
  case 0x0d9:
    return "penguin_l";
  case 0x0da:
    return "castleballoon1";
  case 0x0db:
    return "dossunc";
  case 0x0dc:
    return "dossunc_soko";
  case 0x0dd:
    return "boble";
  case 0x0de:
    return "K_bomb_car";
  case 0x0df:
    return "K_bomb_car_dummy";
  case 0x0e0:
    return "car_body_dummy";
  case 0x0e1:
    return "kart_truck_dummy";
  case 0x0e2:
    return "hanachan";
  case 0x0e3:
    return "seagull";
  case 0x0e4:
    return "moray";
  case 0x0e5:
    return "crab";
  case 0x0e6:
    return "basabasa_dummy";
  case 0x0e7:
    return "CarA2";
  case 0x0e8:
    return "CarA3";
  case 0x0e9:
    return "Hwanwan";
  case 0x0ea:
    return "HeyhoBallGBA";
  case 0x0eb:
    return "Twanwan";
  case 0x0ec:
    return "cruiserR";
  case 0x0ed:
    return "bird";
  case 0x0ee:
    return "sin_itembox";
  case 0x0ef:
    return "Twanwan_ue";
  case 0x0f0:
    return "BossHanachan";
  case 0x0f1:
    return "Kdossunc";
  case 0x0f2:
    return "BossHanachanHead";
  case 0x0f3:
    return "K_bomb_car1";
  case 0x12d:
    return "dummy";
  case 0x12e:
    return "dokan_sfc";
  case 0x12f:
    return "castletree1";
  case 0x130:
    return "castletree1c";
  case 0x131:
    return "castletree2";
  case 0x132:
    return "castleflower1";
  case 0x133:
    return "mariotreeGC";
  case 0x134:
    return "mariotreeGCc";
  case 0x135:
    return "donkytree1GC";
  case 0x136:
    return "donkytree2GC";
  case 0x137:
    return "peachtreeGC";
  case 0x138:
    return "peachtreeGCc";
  case 0x139:
    return "npc_mii_a";
  case 0x13a:
    return "npc_mii_b";
  case 0x13b:
    return "npc_mii_c";
  case 0x13c:
    return "obakeblockSFCc";
  case 0x13d:
    return "WLarrowGC";
  case 0x13e:
    return "WLscreenGC";
  case 0x13f:
    return "WLdokanGC";
  case 0x140:
    return "MarioGo64c";
  case 0x141:
    return "PeachHunsuiGC";
  case 0x142:
    return "kinokoT1";
  case 0x143:
    return "kinokoT2";
  case 0x144:
    return "pylon01";
  case 0x145:
    return "PalmTree";
  case 0x146:
    return "parasol";
  case 0x147:
    return "cruiser";
  case 0x148:
    return "K_sticklift00";
  case 0x149:
    return "heyho2";
  case 0x14a:
    return "HeyhoTreeGBAc";
  case 0x14b:
    return "MFaceBill";
  case 0x14c:
    return "truckChimSmk";
  case 0x14d:
    return "MiiObj01";
  case 0x14e:
    return "MiiObj02";
  case 0x14f:
    return "MiiObj03";
  case 0x150:
    return "gardentreeDS";
  case 0x151:
    return "gardentreeDSc";
  case 0x152:
    return "FlagA1";
  case 0x153:
    return "FlagA2";
  case 0x154:
    return "FlagB1";
  case 0x155:
    return "FlagB2";
  case 0x156:
    return "FlagA3";
  case 0x157:
    return "DKtreeA64";
  case 0x158:
    return "DKtreeA64c";
  case 0x159:
    return "DKtreeB64";
  case 0x15a:
    return "DKtreeB64c";
  case 0x15b:
    return "TownTreeDSc";
  case 0x15c:
    return "Piston";
  case 0x15d:
    return "oilSFC";
  case 0x15e:
    return "DKmarutaGCc";
  case 0x15f:
    return "DKropeGCc";
  case 0x160:
    return "mii_balloon";
  case 0x161:
    return "windmill";
  case 0x162:
    return "dossun";
  case 0x163:
    return "TownTreeDS";
  case 0x164:
    return "Ksticketc";
  case 0x165:
    return "monte_a";
  case 0x166:
    return "MiiStatueM1";
  case 0x167:
    return "ShMiiObj01";
  case 0x168:
    return "ShMiiObj02";
  case 0x169:
    return "ShMiiObj03";
  case 0x16a:
    return "Hanabi";
  case 0x16b:
    return "miiposter";
  case 0x16c:
    return "dk_miiobj00";
  case 0x16d:
    return "light_house";
  case 0x16e:
    return "r_parasol";
  case 0x16f:
    return "obakeblock2SFCc";
  case 0x170:
    return "obakeblock3SFCc";
  case 0x171:
    return "koopaFigure";
  case 0x172:
    return "pukupuku";
  case 0x173:
    return "v_stand1";
  case 0x174:
    return "v_stand2";
  case 0x175:
    return "leaf_effect";
  case 0x176:
    return "karehayama";
  case 0x177:
    return "EarthRing";
  case 0x178:
    return "SpaceSun";
  case 0x179:
    return "BlackHole";
  case 0x17a:
    return "StarRing";
  case 0x17b:
    return "M_obj_kanban";
  case 0x17c:
    return "MiiStatueL1";
  case 0x17d:
    return "MiiStatueD1";
  case 0x17e:
    return "MiiSphinxY1";
  case 0x17f:
    return "MiiSphinxY2";
  case 0x180:
    return "FlagA5";
  case 0x181:
    return "CarB";
  case 0x182:
    return "FlagA4";
  case 0x183:
    return "Steam";
  case 0x184:
    return "Alarm";
  case 0x185:
    return "group_monte_a";
  case 0x186:
    return "MiiStatueL2";
  case 0x187:
    return "MiiStatueD2";
  case 0x188:
    return "MiiStatueP1";
  case 0x189:
    return "SentakuDS";
  case 0x18a:
    return "fks_screen_wii";
  case 0x18b:
    return "KoopaFigure64";
  case 0x18c:
    return "b_teresa";
  case 0x18d:
    return "MiiStatueDK1";
  case 0x18e:
    return "MiiKanban";
  case 0x18f:
    return "BGteresaSFC";
  case 0x191:
    return "kuribo";
  case 0x192:
    return "choropu";
  case 0x193:
    return "cow";
  case 0x194:
    return "pakkun_f";
  case 0x195:
    return "WLfirebarGC";
  case 0x196:
    return "wanwan";
  case 0x197:
    return "poihana";
  case 0x198:
    return "DKrockGC";
  case 0x199:
    return "sanbo";
  case 0x19a:
    return "choropu2";
  case 0x19b:
    return "TruckWagon";
  case 0x19c:
    return "heyho";
  case 0x19d:
    return "Press";
  case 0x19e:
    return "Press_soko";
  case 0x19f:
    return "pile";
  case 0x1a0:
    return "choropu_ground";
  case 0x1a1:
    return "WLfireringGC";
  case 0x1a2:
    return "pakkun_dokan";
  case 0x1a3:
    return "begoman_spike";
  case 0x1a4:
    return "FireSnake";
  case 0x1a5:
    return "koopaFirebar";
  case 0x1a6:
    return "Epropeller";
  case 0x1a7:
    return "dc_pillar_c";
  case 0x1a8:
    return "FireSnake_v";
  case 0x1a9:
    return "honeBall";
  case 0x1aa:
    return "puchi_pakkun";
  case 0x1ab:
    return "sanbo_big";
  case 0x1ac:
    return "sanbo_big_2";
  case 0x1f5:
    return "kinoko_ud";
  case 0x1f6:
    return "kinoko_bend";
  case 0x1f7:
    return "VolcanoRock1";
  case 0x1f8:
    return "bulldozer_left";
  case 0x1f9:
    return "bulldozer_right";
  case 0x1fa:
    return "kinoko_nm";
  case 0x1fb:
    return "Crane";
  case 0x1fc:
    return "VolcanoPiece";
  case 0x1fd:
    return "FlamePole";
  case 0x1fe:
    return "TwistedWay";
  case 0x1ff:
    return "TownBridgeDSc";
  case 0x200:
    return "DKship64";
  case 0x201:
    return "kinoko_kuki";
  case 0x202:
    return "DKturibashiGCc";
  case 0x203:
    return "FlamePoleEff";
  case 0x204:
    return "aurora";
  case 0x205:
    return "venice_saku";
  case 0x206:
    return "casino_roulette";
  case 0x207:
    return "BossField01_OBJ1";
  case 0x208:
    return "dc_pillar";
  case 0x209:
    return "dc_sandcone";
  case 0x20a:
    return "venice_hasi";
  case 0x20b:
    return "venice_gondola";
  case 0x20c:
    return "quicksand";
  case 0x20d:
    return "bblock";
  case 0x20e:
    return "ami";
  case 0x20f:
    return "M_obj_jump";
  case 0x210:
    return "starGate";
  case 0x211:
    return "RM_ring1";
  case 0x212:
    return "FlamePole_v";
  case 0x213:
    return "M_obj_s_jump";
  case 0x214:
    return "InsekiA";
  case 0x215:
    return "InsekiB";
  case 0x216:
    return "FlamePole_v_big";
  case 0x217:
    return "Mdush";
  case 0x218:
    return "HP_pipe";
  case 0x219:
    return "DemoCol";
  case 0x21a:
    return "M_obj_s_jump2";
  case 0x21b:
    return "M_obj_jump2";
  case 0x259:
    return "DonkyCannonGC";
  case 0x25a:
    return "BeltEasy";
  case 0x25b:
    return "BeltCrossing";
  case 0x25c:
    return "BeltCurveA";
  case 0x25d:
    return "BeltCurveB";
  case 0x25e:
    return "escalator";
  case 0x25f:
    return "DonkyCannon_wii";
  case 0x260:
    return "escalator_group";
  case 0x261:
    return "tree_cannon";
  case 0x2bd:
    return "group_enemy_b";
  case 0x2be:
    return "group_enemy_c";
  case 0x2bf:
    return "taimatsu";
  case 0x2c0:
    return "truckChimSmkW";
  case 0x2c1:
    return "Mstand";
  case 0x2c2:
    return "dkmonitor";
  case 0x2c3:
    return "group_enemy_a";
  case 0x2c4:
    return "FlagB3";
  case 0x2c5:
    return "spot";
  case 0x2c6:
    return "group_enemy_d";
  case 0x2c7:
    return "FlagB4";
  case 0x2c8:
    return "group_enemy_e";
  case 0x2c9:
    return "group_monte_L";
  case 0x2ca:
    return "group_enemy_f";
  case 0x2cb:
    return "FallBsA";
  case 0x2cc:
    return "FallBsB";
  case 0x2cd:
    return "FallBsC";
  case 0x2ce:
    return "volsmk";
  case 0x2cf:
    return "ridgemii00";
  case 0x2d0:
    return "Flash_L";
  case 0x2d1:
    return "Flash_B";
  case 0x2d2:
    return "Flash_W";
  case 0x2d3:
    return "Flash_M";
  case 0x2d4:
    return "Flash_S";
  case 0x2d5:
    return "MiiSignNoko";
  case 0x2d6:
    return "UtsuboDokan";
  case 0x2d7:
    return "Spot64";
  case 0x2d8:
    return "DemoEf";
  case 0x2d9:
    return "Fall_MH";
  case 0x2da:
    return "Fall_Y";
  case 0x2db:
    return "DemoJugemu";
  case 0x2dc:
    return "group_enemy_a_demo";
  case 0x2dd:
    return "group_monte_a_demo";
  case 0x2de:
    return "volfall";
  case 0x2df:
    return "MiiStatueM2";
  case 0x2e0:
    return "RhMiiKanban";
  case 0x2e1:
    return "MiiStatueL3";
  case 0x2e2:
    return "MiiSignWario";
  case 0x2e3:
    return "MiiStatueBL1";
  case 0x2e4:
    return "MiiStatueBD1";
  case 0x2e5:
    return "Kamifubuki";
  case 0x2e6:
    return "Crescent64";
  case 0x2e7:
    return "MiiSighKino";
  case 0x2e8:
    return "MiiObjD01";
  case 0x2e9:
    return "MiiObjD02";
  case 0x2ea:
    return "MiiObjD03";
  case 0x2eb:
    return "mare_a";
  case 0x2ec:
    return "mare_b";
  case 0x2ed:
    return "EnvKareha";
  case 0x2ee:
    return "EnvFire";
  case 0x2ef:
    return "EnvSnow";
  case 0x2f0:
    return "M_obj_start";
  case 0x2f1:
    return "EnvKarehaUp";
  case 0x2f2:
    return "M_obj_kanban_y";
  case 0x2f3:
    return "DKfalls";
  default:
    return nullptr;
  }
}

const char* GetNameOfObjectSafe(int id) {
  auto* it = GetNameOfObject(id);
  return it ? it : "?";
}

} // namespace riistudio::lvl
